name: tocmanager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.5
  date_field: ^3.0.1
  datetime_picker_formfield: ^2.0.1
  dropdown_textfield: ^1.0.5
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.1+1
  path_provider: ^2.0.11
    
  
  

  flutter:
    sdk: flutter
  flutter_gen: ^5.2.0
  form_field_validator: ^1.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  responsive_framework: ^0.2.0
  floating_action_bubble: ^1.1.4
  blue_print_pos: ^0.0.14
  permission_handler: ^10.2.0
  flutter_reactive_ble: ^5.0.2
  provider: ^6.0.4
  http: ^0.13.5
  dio: ^5.0.1
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.10
  dropdown_plus: ^0.0.9
  sqlite3_flutter_libs: ^0.5.13
  
  
  

  

dev_dependencies:
  flutter_native_splash: ^2.2.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  

flutter_native_splash:
  color : "#FFFFFF"
  image: assets/logo_toc_manager.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_bleu.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/imgs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy/Satisfy-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Regular.ttf

  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
        

    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Regular.ttf

    # - family: Caveat
    #   fonts:
    #     - asset: fonts/Caveat-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
